### ISSUE TITLE
my_first_chess available soon?

### ISSUE THREAD

**Issue by lyubomyr-shaydariv** [asweigart/my_first_tic_tac_toe#1]
Please.

**Comment by ferdynator** [comment]
:+1: we need this!

**Comment by EvelynSubarrow** [comment]
++

**Comment by yasoob** [comment]
:+1:

**Comment by asweigart** [comment]
I'll get right on it, as soon as I buy a few dozen 3 TB hard drives...

**Comment by Bravo555** [comment]
++

**Comment by marek2901** [comment]
+1

**Comment by joefarebrother** [comment]
And when will my_first_go be available?

**Comment by osilkin98** [comment]
I think `my_first_connect_four` is halfway done. I think @asweigart may need to stock up on the coffee, though.
